### ISSUE TITLE
Close dialog enhancements

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#113]
Just some thoughts on closing a dialog modal.
In order to close a modal all of the following must be done:
1. To have an element with `class="close-modal` that will trigger close dialog.
2. In the dialog controller, include:

```
closeDialog: false,
```
1. In the dialog controller, after the action, include:

```
actions: {
  myAction: function(){
      // do something;
      this.set('closeDialog', true);
   }
}
```

I was just wondering if this is abundant and a simple `class="close-modal"` would be enough to close the dialog...

**Comment by athinab** [comment]
I've added some comments in order to explain why we have 2 ways to close a dialog.
In a nutshell if you want to do things before you trigger the closing of the dialog, you can use the property closeDialog.
Please, check and the related commit.

**Comment by olgabrani** [comment]
:tulip: LGTM
