### ISSUE TITLE
Uniform action names

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#125]
If we compare [dialogs/create-dir.hbs](https://github.com/olgabrani/synnefo/blob/cbcf32d660b8ce53a9c1499b420f9df240560fdd/snf-ui-app/ui-web/app/templates/dialogs/create-dir.hbs) and [dialogs/create-container.hbs](https://github.com/olgabrani/synnefo/blob/cbcf32d660b8ce53a9c1499b420f9df240560fdd/snf-ui-app/ui-web/app/templates/dialogs/create-container.hbs), we can see that similar actions follow different naming conventions:

action 'validateCreation' 'createDir'
action 'validateCreate' 'createContainer'

We should decide on naming conventions and stick to them.
 An overall name control must be done for all actions.

**Comment by athinab** [comment]
For the particular example I think I prefer the "validateCreation".
Probably, in most cases, it is convenient to name actions with a verb or with a verb and a noun.

Do you agree?

**Comment by athinab** [comment]
This is related with olgabrani/synnefo#54

**Comment by olgabrani** [comment]
Fine by me

**Comment by vinilios** [comment]
+1
