### ISSUE TITLE
Empty container

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#16]
### Goal

Perform "empty Container" action
### Considerations

In order to empty a container, the same ajax call is to be sent as when it is deleted, but with the option `delimiter=/` as data to the DELETE request.
One way to do this is to implement a custom adapter method, called `emptyContainer` and then call it in an analogous way as in deleteRecord:

```
actions: {
    deleteContainer: function(){
      var container = this.get('model');
      container.deleteRecord();
      container.save();
    }
  }
```

The problem is that deleteRecord is a store's method, while I want to call an adapter's method.

Is this the correct way to handle this? 
If yes, how do I access the adapter from the controller?

**Comment by vinilios** [comment]
You can access store from the controller and model's adapter from the store. This way, two new methods should be implemented for the application store and model adapter accordingly.

**Comment by olgabrani** [comment]
My thoughts exactly :+1:
But how do I add a custom method for the store?

**Comment by vinilios** [comment]
We can either reopen the ember-data store or set a custom store to the application. I'm in favor of the second option. I guess the following should do the trick, haven't tested it though.

``` javascript
var SynnefoStore = Ember.Store.extend({
  ...custom methods here....
});
UiWeb.Store = SynnefoStore
```

**Comment by olgabrani** [comment]
6736753b0f3378c1d9b174a0b5f3d31be44a74c7

@vinilios 

Is this the proper way to do this?

**Comment by vinilios** [comment]
LGTM so far. I'm a bit diffident on the overall approach though. I guess we have to go all
the way and implement the actions down to the api ajax call to see what might
come up.
