### ISSUE TITLE
Uniform tooltips

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#161]
Currently we use [hint css](http://kushagragour.in/lab/hint/) and the browser's default tooltip.
We should decide on one type of tooltip.

**Comment by olgabrani** [comment]
@AthinaB how about using [foundation's tooltip](http://foundation.zurb.com/docs/components/tooltips.html)?

**Comment by athinab** [comment]
From now on we will try to use foundation tooltips.
If you want to use tooltips, you need to extend the `TooltipMixin` in the view that will have the dom element with the tooltip.
In the html you need add the attr `data-tooltip` and a `title` in the dom element.

this approach should work and for elements that are rendered dynamically but not for children views or templates.

Main commit: ebc3c87573c27081925c10e3308670cd560d107f
