### ISSUE TITLE
Create new dir in empty container doesn't show it

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#169]
The dir is created successfully but the objects list looks empty .

**Comment by athinab** [comment]
I think that refresh.js throws an error:
`Uncaught TypeError: object is not a function`
 for the line 201:
`spec.callee();`

**Comment by vinilios** [comment]
It seems that `model` property of objects controller is set to undefined in the 
case of an empty container. Is this intentional ?

**Comment by athinab** [comment]
I don't think so.
I will look into it.

2015-06-08 15:31 GMT+03:00 Kostas Papadimitriou notifications@github.com:
