### ISSUE TITLE
Cannot assign project when creating new container

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#17]
When the action is called from the controller, `this.store.createRecord`  creates the record client side.
Then, the model is saved to the backend when the method `save()` is invoked.
The `createRecord` is a Store's method that calls the adapter's `createRecord` method, which in turns is overwritten by the restAdatpter's `createRecord` that is last and not least overwritten by our custom ContainerRestAdapter `createRecord` method.
(All these are mainly speculations :dizzy_face: ) 

However, I cannot assign a project to the newly created container.
The project id is set in the headers [as shown here, ](https://github.com/olgabrani/synnefo/blob/release-0.16-newui/snf-ui-app/ui-web/app/adapters/container.js#L36) that are sent to the PUT API call...

**Comment by vinilios** [comment]
I'm not sure i undestand the issue here. The container creation with project assigned seems to succeed on my demo deployment. That's after changing the hardcoded project uuid :)

**Comment by olgabrani** [comment]
The problem is that I cannot assign a project to a newly created container without the **hardcoded** project uuid.

I suspect it has something to do with the project serializer.
The store's `createRecord` is responsible for serializing  the data provided and return a record for the adapter.
The project id is present before the store's `createRecord` is called and then missing in the adapter's record.

**Comment by vinilios** [comment]
I see. Yet another ember-data annoying behaviour. The only way i see to resolve this is by leveraging the record.get('project') promise. e.g.

``` javascript
return new Ember.RSVP.Promise(function(resolve, reject) {
    record.get('project').then(function(project) {
        headers['X-Container-Polixy-Project']: project.get('id');
        Ember.$.ajax(...................)
    }, function() { Ember.run(null, reject, "Invalid project"});
});
```

**Comment by olgabrani** [comment]
:cake:
