### ISSUE TITLE
Sidebar shared with me dir-tree does not filter containers/folders properly

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#172]
Let's assume that I have shared some objects with myself.
Shared with me dir-tree in sidebar shows **all** of my containers/folders instead of showing only the containers/folders that are **either shared with me either contain objects that are shared with me**.

According to [Pithos API](https://www.synnefo.org/docs/synnefo/latest/object-api-guide.html), 
we can use a query parameter to filter results, so that the call returns only the 
objects/containers that are shared to me.

What I did can be found here:

https://github.com/olgabrani/synnefo/commit/23b0173db9b0f19a59423c8673b63dff8eca5c75

Let's say that I have a container named `0` and inside it a folder named `test`, that contains a shared object `foo.txt`.

The caveat with the above commit is that the call:

```
https://synnefo.live/pithos/object-store/v1/{uuid}/0?path=/&shared=true
```

will return zero results (as the folder `test` is not shared), thus not allowing any path to the object `foo.txt`.

Any ideas on how to overcome this problem?
@vinilios

**Comment by vinilios** [comment]
Does this still apply ? It seems that i cannot see my own shares within the "shared with me" tree.

**Comment by olgabrani** [comment]
The shared with me tree shows only the containers that are shared with me by others.
The problem is that is someone shares with me the object `pithos/folder-1/folder-2/foo.txt` and the objects 
`pithos/folder-1` and `pithos/folder-1/folder-2` are not shared with me, I have no way of accessing the foo.txt file from the sidebar "file browser".

**Comment by olgabrani** [comment]
Moved to private repo tracking system
