### ISSUE TITLE
Useful resources

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#18]
### Ember resources
- [Ember CLI Addon for Lightbox2](https://ramybenaroya.github.io/ember-cli-lightbox/)

The addon has been tested and is easily installed:

```
$ npm install ember-cli-lightbox --save-dev
$ ember g ember-cli-lightbox
```
- [Ember CLI Pagination](https://github.com/mharris717/ember-cli-pagination)
- [Ember Admin](https://github.com/dockyard/ember-admin)
- [Ember loading state](http://balinterdi.com/2014/06/18/indicating-progress-loading-routes-in-ember-dot-js.html)
- [Drag&Drop file upload](https://github.com/Wildhoney/EmberDroplet)
- [Automatic breadcrumb in Ember](http://blog.salsify.com/engineering/automatic-breadcrumbs-in-ember.js) vs [ember-breadcrumbs](https://github.com/chrisfarber/ember-breadcrumbs)
- [Ember form validation](https://github.com/maestrooo/ember-cli-html5-validation)
- [Ember JSBin Examples](https://gist.github.com/rwjblue/8816372)

**Comment by athinab** [comment]
### UI resources

Here we can keep a list of resources regarding scss, html, ui structure, ui design etc...
- [Naming colors](http://www.colorhexa.com/color-names)
- [Interactive float labels](http://codepen.io/aaronbarker/pen/tIprm) (also check [here](http://azumbrunnen.me/blog/interactive-float-labels/))
- [Hover effects for buttons](http://tympanus.net/Development/IconHoverEffects/)

**Comment by olgabrani** [comment]
### Design resources

Ideas about design or themes

**Comment by olgabrani** [comment]
### Testing resources

We must choose a javascript testing framework for the app
