### ISSUE TITLE
Bug in Opera browser

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#182]
Strangely, in Opera, when visiting the newui homepage, I get the following error:

```
 TypeError: undefined is not a function
```

that references the line:

```
      delimiter: '-'.repeat(72) + '\n',
```

of locales/en.js file.

**Comment by athinab** [comment]
I tried to see this, but I cannot reproduce it with Opera 30.0.1835.59.

**Comment by athinab** [comment]
For now, we can close it.
