### ISSUE TITLE
Not valid behaviour of rename

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#183]
Object name: "a"
Make the following renames: "a" -> "b" -> "a"
If you try to name the object "a" for the second time the input shows the error: "Already exists"

**Comment by athinab** [comment]
It seems that there is the same problem with the action create, after deletion or cut.
I think that the initial model doesn't get removed from the store.

**Comment by olgabrani** [comment]
The rename bug is fixed by c4c8d9a582d40666a0f7b741575375282e7ff53e
