### ISSUE TITLE
Delete last user from group

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#185]
If you delete the last user of the group, the group gets deleted. But there is a case where a user wants to change all members but, share them all the files that were shared with the particular group.

So, maybe it would be useful to add a confirmation/explanatory popover when the last user is going to be deleted.

**Comment by vinilios** [comment]
Is it possible for a user to include herself as a group user ? If so we could probably use it as a hack to solve the issue. UI could covertly inject the group owner user uuid in users list every time it gets modified/created.

**Comment by athinab** [comment]
Nice trick!
I'll give it a try!

**Comment by olgabrani** [comment]
Moved to private repo tracking system
