### ISSUE TITLE
Handle hyphens (-) and colons (:) in group names

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#213]
It seems that Pithos server can't have hyphens in the name of the group and encodeURIComponent doesn't affect them. Should we forbid them?

**Comment by vinilios** [comment]
since server says so....

If i recall correctly groups information is communicated via HTTP headers, if so, i would bet that hyphens won't be the only character causing issues.

**Comment by athinab** [comment]
Colons shouldn't been allowed in order to avoid parsing bug.
The bug is caused because colons are used by the server to split data.
For example see the property x_object_sharing.
