### ISSUE TITLE
Uploaded files are not shown in objects lists

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#217]
Files are uploaded normally, but they don't appear in objects list.
They only appear after refresh.

This bug does not happen when I try to upload in container level, but only to inner folders.

**Comment by olgabrani** [comment]
I checked the following and it seems ok:
- [x] Upload files to a container
- [x] Drag & drop files to a container
- [x] Upload files to a container/folder
- [x] Drag & drop files to a container/folder
- [x] Upload files to a shared with me container/folder

@AthinaB could you please check it as well? Thanks in advance :rose: 

Note that I applied the inverse of [this](https://github.com/vinilios/synnefo/commit/33de48858238bfd9ecf48eaca75d1441191bfa28#diff-1fedfcb6103774404f28f9e64850b8c4R76) to check

**Comment by athinab** [comment]
When you say "refresh" you mean when the user presses the corresponding
button?
Should I see it immediately after the upload is completed (before another get request is completed)?

2015-08-12 13:10 GMT+03:00 Olga Brani notifications@github.com:

**Comment by athinab** [comment]
I think is ok, so I am closing it.
