### ISSUE TITLE
How to handle img src for objects in containers

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#24]
Currently, in Pithos, the img src for an image, has the format:
`https://pithos.okeanos.grnet.gr/ui/view/<user_id>/<container_id>/<object_path>`

What is the proper way to handle this?
Where does **/ui/view/** come from?
Currently, ember does not recognise the above url scheme.
But should it?

Finally, `<container_id>` is a parameter that in only passed though the route to the model query.
How will it be transmitted to the ObjectController? 

Latest implementation: 1d270aebfc7ac46f2e0342e52c1c283142f23cc8

**Comment by vinilios** [comment]
There is a related setting which indicates the host from which pithos public files are served,

``` javsacript
    otherProperties.STORAGE_VIEW_URL = "https://pithos.okeanos.grnet.gr/ui/view/";
```

Both container (as a store record) and container_id can be set to the controller in setupController method, e.g.

``` javascript
model: function(params) {
    this.set('container_id', params.container_id);
    return this.store....
},
setupController: function(controller, model) {
    controller.set('model', model);
    controller.set('container', this.store.find('container', this.get('container_id')))
    controller.set('container_id', this.get('container_id'))
}
```

**Comment by vinilios** [comment]
Hmm, regarding the resloving of container and container_id. Another aproach, which seems as a finer match to the emberjs resourceful logic, would be to have objectslist route nested within the container route.

**Comment by olgabrani** [comment]
When using this img path: `https://pithos.synnefo.live/ui/view/< uuid >/pithos/kitten.jpg`, I get:

```
Error: Assertion Failed: The URL '/view/kitten.jpg' did not match any routes in your application
```

How do I handle ember routes and img src? @vinilios

**Comment by vinilios** [comment]
The view that serves the image contents is registered in pithos component namespace. Most probably, since you used snf-deploy to install synnefo, the view api should be "/pithos/ui/view" instead.
