### ISSUE TITLE
Observes() observes property that is not present

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#26]
be94754

I  wonder if this is the ember way to handle events on project selection change.
ContainerController has a watchProject method that observes changes in `selectedProject` property in the selected projects < select >.
This is used for containers view where one can reassign each individual container.

However, when we navigate to single container view, there is no selectedProject property (at least not yet), and thus throwing a javascript error of `cannot get property of undefined`.

It seems to me, that the solution I came up with is a little dirty. :disappointed: 

It works however.

**Comment by vinilios** [comment]
How about componentizing the project select widget ?

**Comment by vinilios** [comment]
Oh, related to the use of observer to watch the project change, i don't see any problem with this.

**Comment by olgabrani** [comment]
ba49d2173db510b2e396e8261002c90fda1b8e4a

Apparently, the `selection` property of Ember's `view` "select" has to be an element of it `content` array property.
https://github.com/emberjs/ember.js/blob/v1.10.0/packages/ember-views/lib/views/select.js#L410
Consequently, if we set `selection` to model's project without extracting it from `content`, it is not found by the view.
