### ISSUE TITLE
Missing newly created object id

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#30]
When a new directory object is created, it has no id and consequently, does not appear immediately upon creation in the template.
The problem is that the id is assigned to the object, **after** it has been created and I don't know how to make the store aware of it.

**Comment by vinilios** [comment]
Is it possible use object's path (including container name) as id for object records ? 
- I guess sooner or later the object's path property should be resolved and used somehow.
- The uuid seems to be deprecated in swift API (the api pithos is based on) or it is a custom synnefo 
  addition. Although it's not a hard requirement swift API compatibility may end up as a beneficial feature.

Not excited ? A couple of alternatives,
- Do not locally store a record after the create call. Instead refresh the container objects, hopefully the 
  new object will be added automatically via the object list response.
- Right after the create ajax call, do a details call to the created object path. The response is supposed to 
  contain the object id.

**Comment by olgabrani** [comment]
It is not such a bad idea to use the object's path (including container's name) as id.

However, what happens when we move an  object to trash? Its id will change?

**Comment by vinilios** [comment]
I guess so, trash is yet another folder (or container, i'm not sure). Moving a file to trash is like moving it to any other folder.

**Comment by olgabrani** [comment]
So, whenever a file is moved its id changes?
