### ISSUE TITLE
Router.js updated schema

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#37]
Current router has the following layout:

```
Router.map(function() {
  this.resource('projects');
  this.resource('project', { path: '/projects/:project_id' });
  this.resource('containers');
  this.resource('container', { path: '/containers/:container_id'}, function(){
    this.resource('objects', { path: '/*current_path'}, function(){
      this.resource('object', function(){
        this.route('versions');
      });
    });
  });
  this.resource('quotas');
  this.route('groups');
});
```

The problem with the current approach is that schematically, **containers** and **groups** are not under the account level, as the should according to [the official API docs](https://www.synnefo.org/docs/synnefo/latest/object-api-guide.html#the-pithos-api)

Maybe we should use user account as a top level url, like this:
- Account 
  - Groups
  - Containers
    - Objects

This way '/' (account) will be returning groups and containers.

@vinilios

**Comment by olgabrani** [comment]
Account model would have:

```
containers: DS.hasMany('container'),
groups: DS.hasMany('group')
```

**Comment by vinilios** [comment]
At the moment i think we can safely assume that UI's '/' path acts as an alias to the /< account >/ store api endpoint, since the user has already signed in and we do not (yet) support user access to multiple accounts. I'm weakly leaning in favour of keeping things the way they are now as long as the current implementation is not causing any additional issues.

**Comment by olgabrani** [comment]
The current implementation requires the presence of two or more models in one page. 
This can be implemented, but I would rather follow ember's logic that would have containers and groups as attributes of the user's account.

I will probably try it anyway to see if there are any side effects.

**Comment by vinilios** [comment]
Which route/view requires two models ?

**Comment by olgabrani** [comment]
```
this.resource('container', { path: '/containers/:container_id'},
```

I just feel it is best to follow Pithos API architecture (account has groups and containers)

**Comment by olgabrani** [comment]
Although **schematically**, the `account` model `hasMany` containers and groups, we will keep the current implementation as it appears its complications are more than its advantages.
