### ISSUE TITLE
Handling copy paste of object with the same name

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#38]
### Currently

When you cut/copy an object and you want to paste it to  its current path, there is no option to do this.
When you cut/copy an object and you want to paste it to another path, where there is already another object with the same name, then the object is pasted and the previous object in the new path is overwritten (or to be more accurate, a new version of this object is created).
### Alternative approach

When you cut/copy an object whose name already exists, a new object by the name name(1) is created.
### Discussion

Is the current behaviour the desired one? 
The truth is that current behaviour is a more bash-like and favors versioning. 
The alternative approach would be more user friendly thought.

@vinilios

**Comment by vinilios** [comment]
How about the common file manager approach ?  The one with the intermediate step which prompts the user to decide whether or not to overwrite the existing file or rename the one to be moved ?
