### ISSUE TITLE
Containers usage

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#42]
The following information is available:
- Diskspace used by the current user per project.
- Total diskspace used by all members of a project per project.
- Max allowed diskspace usage for the current user per project.
- Really available diskspace for the current user per project.

Which usage numbers are we going to show to the user and how are we going to present this info?

**Comment by athinab** [comment]
Probably, in pithos pages we should keep the most essential information about storage quotas.

In the the page with the list of the containers, we can put a progress bar for each container that will show its **size** relatively to the **effective diskspace limit (really available)** or **free space (effective limit - used by current user)** of the assigned project.

We can also have an info icon at a side (probably visible at all time?). If the user clicks on the icon, an area/popover will appear with a progress bar for each project that will reflect **diskspace used by the current user** (sum of size of all its containers) relatively to the **effective limit**. If the effective limit is less than the max limit per project member, we can have an explanatory message and a link to dashboard/usage page.

If we notice that the above approach is confusing or fuzzy for the users we can just show for each container its size with numbers and the info icon with the progress bars of total usage per project.

**Comment by athinab** [comment]
We finally add an area with the total usage of each project and the size of each container will be displayed only with numbers. This seems to be the most efficient way of show that type of info without risking to disorient any users.

For visual enhancement we could have a view where each container will be in a tile and beneath its name and the reassign selection list will have a small pie chart with 3 slices:
- Size of container
- Size of all the other containers of the particular project
- Free size

At the bottom of the tile we can have the action buttons.

**Comment by athinab** [comment]
Special handling for over quota usage is required, too.
