### ISSUE TITLE
Delete (correction: move to trash) an object and then try to create another one

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#44]
I've noticed that you cannot create a directory after you have deleted another object.
Something goes wrong...

**Comment by olgabrani** [comment]
I could not reproduce it.
Could you write the exact steps you did?

**Comment by athinab** [comment]
I am sorry I wrote "delete", but I meant "move to trash".

I don't have much more info to add I think. I am in a container, I click on the trash icon and then I write something in the create dir input. Then when I press save I can't see it below, as usual.

**Comment by olgabrani** [comment]
Ok, I can reproduce it with "move to trash" action.
