### ISSUE TITLE
Controller property not updated when model property changes

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#48]
d8a0b9cf4f407814204b366d4ece8567aca7f83b

If you have a group with more than one users, and you delete one user, the user is not removed visually from the group's users.

That is odd, because in the group's controller, there is a property `members` that is updated when group's `uuids` changes (which is our case).

Any ideas?

@vinilios

**Comment by vinilios** [comment]
The uuid property observer is hooked to the _members property. The _members property won't get triggered unless explicity accessed from a point in code. We could either convert _members to use `observes` computed property, or additionally make members property to watch uuids for changes.

**Comment by olgabrani** [comment]
Fixed by 72a417541853aef10f7138240c78a9e13c2a01a1

**Comment by olgabrani** [comment]
[Observers and object initialization](http://emberjs.com/guides/object-model/observers/#toc_observers-and-object-initialization) proved useful.
