### ISSUE TITLE
How is 'extraHeaders' used in snf/adapters/base.js?

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#59]
Apparently, one can set extra headers for ajax call in `snf/adapters/base.js`  by using `extraHeaders` parameter.
I could not use it in `adapters/container.js`...
I tried to do use it here https://github.com/olgabrani/synnefo/blob/23b9aa888b00186991224dbea8820a03cdab37e5/snf-ui-app/ui-web/app/adapters/container.js#L42:

```
this.set('extraHeaders', {'Accept', 'text/plain'});
var headers = this.get('headers');
```

but headers seemed untouched by extraHeaders parameter.
Any ideas?

**Comment by vinilios** [comment]
extraHeaders is not really useful in your case. Setting extraHeaders at this point is useless and probably cause issues later on considering that all requests from that point will set the 'text/plain' header. The extraHeaders property is used define _per adapter_ additional headers (I see now that it's not really useful and maybe we should deprecate the functionality) and not per request ones (this would be really useful but seems non trivial to implement with current ember-data semantics.

**Comment by olgabrani** [comment]
Ok, that makes sense.
I will keep the current implementation per request that works just fine:

```
var headers = this.get('headers');
headers['foo'] = 'bar';
```

Thanks :beer:
