### ISSUE TITLE
Proper way to empty a container and then delete it

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#60]
When the user deletes the container, two actions must happen:
The container must first be emptied and after this is done, it must be deleted.

In container's adapter, there are two methods for that: `emptyContainer` and `deleteRecord`.
However, what is the recommended way to handle the actions synchronisation?
Should I call the `emptyContainer` from the controller and then call the `deleteRecord`?
Should `emptyContainer` be called from within container's adapter `deleteRecord` method?

[adapters/container.js](https://github.com/olgabrani/synnefo/blob/23b9aa888b00186991224dbea8820a03cdab37e5/snf-ui-app/ui-web/app/adapters/container.js)
[controllers/container.js](https://github.com/olgabrani/synnefo/blob/23b9aa888b00186991224dbea8820a03cdab37e5/snf-ui-app/ui-web/app/controllers/container.js)

**Comment by vinilios** [comment]
How about creating an additional emptyAndDelete method ? It shouldn't be hard to implement. You just have to chain/join the promises returned from the underlying methods into a new one. I would take a look on RSVP module helpers to check if an existing helper for such case already exists.

**Comment by olgabrani** [comment]
https://github.com/olgabrani/synnefo/blob/release-0.16-newui/snf-ui-app/ui-web/app/controllers/container.js#L49-L51

If you create a record and without refreshing the view, you try to delete it, you get the following error:
`Error: Attempted to handle event`deleteRecord`on <ui-web@model:container::ember808:5> while in state root.loaded.created.inFlight.`

My guess is it has to do something with the server's response when a container is created.
Any ideas?
