### ISSUE TITLE
Pagination & sorting for container's objects

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#66]

**Comment by athinab** [comment]
In list view, the user will be able to sort the items by clicking the title of the corresponding column.
In grid view we probably should add a button that the user can click and select the sorting key that wants to use from the available keys.

Maybe we could have the button and in the list view (also keep and the click-able title)

**Comment by vinilios** [comment]
On 12/01/15 15:03, Athina Bekakou wrote:

> In list view, the user will be able to sort the items by clicking the title of the corresponding column.
> In grid view we probably should add a button that the user can click and select the sorting key that wants to use from the available keys.
> 
> Maybe we could have the button and in the list view (also keep and the click-able title)    
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/olgabrani/synnefo/issues/66#issuecomment-69566448

What are the benefits, ux wise, of the grid view in the context of
file/dir listing ?

## 

kpap

**Comment by athinab** [comment]
In my opinion, grid view with larger icons and less information is a simpler (minimal) approach of the layout, that could be more restful to the eye. Large icons, that may indicate the type of each file or maybe icons that are a preview of the corresponding file could be handy. If we attach and an action to each icon, like "play", maybe it's a good practice to have a view where the clickable areas are oversized (and it would be easier to use with a touch screen).

I suppose, if we could have a fast preview of each image, it would be pleasant to see the images of a folder as tiles. But we should probably conclude first if we can give the ability of preview images, pdfs etc (without killing the performance of the app).

Also, I think that the users feel nice when they can decide a few things regarding the look and feel of the app that they use (theme and layout). So, if it is not difficult for us to give them some choices (just a small number of choices) I would propose to do it.

What do you think?

**Comment by vinilios** [comment]
Oh, ok then.

**Comment by olgabrani** [comment]
Sorting functionality has been implemented 3ce16d4ee80b3c5e961ae5ee88d870df1e610f9e.
We will probably opt for infinite scroll instead of standard pagination, but this will be part of performance optimisation consideration, so the issue closes for now.
