### ISSUE TITLE
Cannot add users to group multiple times

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#75]
#### How to reproduce the bug

If I have a group and I add a user, the new user is added normally to the group's users.
If I try to add another user without refreshing the page, the new user is not added.
#### debugging info

[group adapter](https://github.com/olgabrani/synnefo/blob/bf617b325f2915e1f9af1d3d1347d39b02d60994/snf-ui-app/ui-web/app/adapters/group.js#L42)
It is strange that the correct list of users is sent to the adapter.
However, during the mapping loop [here](https://github.com/olgabrani/synnefo/blob/bf617b325f2915e1f9af1d3d1347d39b02d60994/snf-ui-app/ui-web/app/adapters/group.js#L43-#L46) there is one user less :disappointed:

**Comment by vinilios** [comment]
The commit seems to fix the issue. Further investigation of the strange behaviour might still come in hand for future reference though.
