### ISSUE TITLE
Create tree view

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#78]
Create a tree view of containers, folders, files etc.
This could be placed in a sidebar and maybe could be useful when the user moves an object or restores it from trash.

**Comment by olgabrani** [comment]
This could prove useful: [ember-idx-tree](https://www.npmjs.com/package/ember-idx-tree)

**Comment by olgabrani** [comment]
6aa3b6000698b82f35fb92d179623e9d1d0bbcd1

Some future improvements could include:
-  Do not toggle folder icon if the folder does not have any subfolders
-  Do not refresh `dir-tree` component when  changing url.
