### ISSUE TITLE
Groups with special chars in their name are not displayed properly

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#81]
If the names have characters such as "/", "|", "\", "[", "{" the ui displays only the part of the name before this character.

Also, if the displayed part is the same with the name of another group, it is not displayed at all.

**Comment by athinab** [comment]
Also group names with greek letters (encoded) don't get displayed.

**Comment by vinilios** [comment]
I guess ajax request helper doesn't allow strings containing special characters to be set in request headers. We should appropriately encode/decode them. Using [encode|decode]URIComponent is a start, but additional handling might be needed for some characters.
