### ISSUE TITLE
Initialize foundation()

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#82]
I am not sure about how we are going to initialize foundation().
We could [include it in our application view](https://coderwall.com/p/azjwaq/how-to-initialize-foundation-in-your-ember-app), but I have doubts that it is considered ember best practice .
We could also implicitly use it when needed as we have done [in dialog view](https://github.com/olgabrani/synnefo/blob/release-0.16-newui/snf-ui-app/ui-web/app/views/dialog.js#L8-L17)

**Comment by vinilios** [comment]
The most difficult part of foundation integration to ember app is that we don't have a direct way to identify whether or not a view (including nested subview objects) should trigger foundation initialization code. Hooking it in the application view would be simple if foundation could handle dynamicaly inserted elements and automatically initialize its state as they get inserted in DOM. I don't think this is supported by foundation. A quick and dirty way to resolve this is pointed out in the comments of the blog post you referred. 

``` javascript
Ember.View.reopen({
        didInsertElement : function(){
        this._super();
        Ember.run.scheduleOnce('afterRender', this, this.afterRenderEvent);
    },
    afterRenderEvent : function(){
        Ember.$(document).foundation();
    }
});
```

The apparent introduced overhead should hopefully not cause major issues, especially while we are in the early development phase. A finer approach would require tagging views which contain fountation specific elements and optionally foundation initialization code.

**Comment by olgabrani** [comment]
Ιn that case, I would prefer to initialize foundation when it is needed by a view or a component, as @AthinaB did in the dialog view.

**Comment by vinilios** [comment]
ack

**Comment by vinilios** [comment]
It seems that foundation js library includes some additional functionality in regard to dynamic html content [1]. Although the feature is not thoughrouly exmplained, it seems that we could leverage the 'reflow' parameter to resolve the aforementioned issues.

[1] http://foundation.zurb.com/docs/javascript.html [Adding New Content After Page Load]
